on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-check:
    name: Checks if lint and build works
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - run: yarn install
        shell: bash

      - run: yarn build
        shell: bash

      - run: yarn lint
        shell: bash
